package model;
// Generated 22 Dec, 2019 2:40:36 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * ClientContact generated by hbm2java
 */
@Entity
@Table(name = "client_contact", catalog = "windmills")
public class ClientContact implements java.io.Serializable {

	private int clientconId;
	private ClientDetails clientdetails;
	private User user;
	private String name;
	private String email;
	private String phone;
	private Date createDate;
	private Date modifiedDate;
	private Date deletedDate;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "clientcon_Id", unique = true, nullable = false)
	public int getClientconId() {
		return clientconId;
	}

	public void setClientconId(int clientconId) {
		this.clientconId = clientconId;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "client_id" , nullable = false)
	public ClientDetails getClientdetails() {
		return clientdetails;
	}

	public void setClientdetails(ClientDetails clientdetails) {
		this.clientdetails = clientdetails;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	@Column(name = "email")
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	
	@Column(name = "phone", length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_date", length = 19)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deleted_date", length = 19)
	public Date getDeletedDate() {
		return this.deletedDate;
	}

	public void setDeletedDate(Date deletedDate) {
		this.deletedDate = deletedDate;
	}

	
	
}
